version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: bff-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  redis_data:
